/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#d8e3fb",
        "tertiary": "#615b77",
        "on-primary-fixed": "#003993",
        "on-tertiary-fixed-variant": "#5c5672",
        "on-secondary-fixed": "#354053",
        "on-error": "#fff7f6",
        "surface-container-low": "#f1f4f7",
        "error-dim": "#4e0309",
        "surface": "#f8f9fb",
        "secondary": "#545f74",
        "on-tertiary": "#fcf7ff",
        "inverse-surface": "#0c0f10",
        "on-tertiary-container": "#524c68",
        "on-surface": "#2b3438",
        "on-secondary-container": "#475266",
        "on-secondary-fixed-variant": "#515c70",
        "error": "#9f403d",
        "primary-container": "#dae2ff",
        "on-primary-fixed-variant": "#0253cd",
        "on-tertiary-fixed": "#3f3a54",
        "primary-fixed": "#dae2ff",
        "surface-container": "#eaeef2",
        "tertiary-container": "#e3dbfd",
        "primary-fixed-dim": "#c6d3ff",
        "inverse-primary": "#5c8bff",
        "on-background": "#2b3438",
        "on-primary": "#f8f7ff",
        "on-error-container": "#752121",
        "secondary-fixed": "#d8e3fb",
        "primary-dim": "#004aba",
        "surface-container-lowest": "#ffffff",
        "tertiary-dim": "#554f6b",
        "surface-dim": "#d1dce2",
        "primary": "#0c56d0",
        "on-surface-variant": "#586065",
        "background": "#f8f9fb",
        "surface-container-highest": "#dbe4ea",
        "secondary-fixed-dim": "#c9d5ed",
        "outline-variant": "#aab3b9",
        "surface-tint": "#0c56d0",
        "error-container": "#fe8983",
        "inverse-on-surface": "#9b9d9f",
        "surface-bright": "#f8f9fb",
        "outline": "#737c81",
        "surface-container-high": "#e2e9ee",
        "tertiary-fixed-dim": "#d5cdee",
        "tertiary-fixed": "#e3dbfd",
        "surface-variant": "#dbe4ea",
        "on-secondary": "#f8f8ff",
        "secondary-dim": "#485368",
        "on-primary-container": "#004ab9"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
